/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Acceso;
import Modelo.Coche;
import java.awt.BorderLayout;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {

        initComponents();
        setTitle("Base de Datos de Coches");
        ImageIcon imgIcono=new ImageIcon("src/favicon.png");
        setIconImage(imgIcono.getImage());
        setResizable(false);
        setLocationRelativeTo(null);

      
        
        
        
        
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCoches = new javax.swing.JMenu();
        menuAlta = new javax.swing.JMenuItem();
        menuConsultas = new javax.swing.JMenuItem();
        menuLecturaBD = new javax.swing.JMenuItem();
        menuFicheros = new javax.swing.JMenu();
        menuCrearFichero = new javax.swing.JMenuItem();
        menuLeerFichero = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coche.png"))); // NOI18N

        menuCoches.setText("Coches");

        menuAlta.setText("Alta coches");
        menuAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAltaActionPerformed(evt);
            }
        });
        menuCoches.add(menuAlta);

        menuConsultas.setText("Consultas");
        menuConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultasActionPerformed(evt);
            }
        });
        menuCoches.add(menuConsultas);

        menuLecturaBD.setText("Lectura BBDD");
        menuLecturaBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLecturaBDActionPerformed(evt);
            }
        });
        menuCoches.add(menuLecturaBD);

        jMenuBar1.add(menuCoches);

        menuFicheros.setText("Ficheros Binarios");

        menuCrearFichero.setText("Crear fichero");
        menuCrearFichero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCrearFicheroActionPerformed(evt);
            }
        });
        menuFicheros.add(menuCrearFichero);

        menuLeerFichero.setText("Leer fichero");
        menuLeerFichero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLeerFicheroActionPerformed(evt);
            }
        });
        menuFicheros.add(menuLeerFichero);

        jMenuBar1.add(menuFicheros);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAltaActionPerformed
        AltaCoche acview=new AltaCoche(this,true);
        acview.setVisible(true);
    }//GEN-LAST:event_menuAltaActionPerformed

    private void menuConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultasActionPerformed
        Consultas acview=new Consultas(this,true);
        acview.setVisible(true);
    }//GEN-LAST:event_menuConsultasActionPerformed

    private void menuLecturaBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLecturaBDActionPerformed
        Lectura acview=new Lectura(this,true);
        acview.setVisible(true);
    }//GEN-LAST:event_menuLecturaBDActionPerformed

    private void menuCrearFicheroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCrearFicheroActionPerformed
        int v = JOptionPane.showConfirmDialog(null, "¿Quieres guardarlos datos de vehículos diesel en el fichero binario diesel.dat? ", "Mensaje de confirmacion", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (v == 0) {
                Acceso acc=new Acceso();
                ArrayList<Coche> listaCoches = acc.readfCoches();
                acc.writeDieselSelection(listaCoches);
                JOptionPane.showMessageDialog(null, "Fichero guardado",
                "Guardado", JOptionPane.INFORMATION_MESSAGE);
            }
    }//GEN-LAST:event_menuCrearFicheroActionPerformed

    private void menuLeerFicheroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLeerFicheroActionPerformed
        FicheroBinario acview=new FicheroBinario(this,true);
        acview.setVisible(true);
    }//GEN-LAST:event_menuLeerFicheroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuAlta;
    private javax.swing.JMenu menuCoches;
    private javax.swing.JMenuItem menuConsultas;
    private javax.swing.JMenuItem menuCrearFichero;
    private javax.swing.JMenu menuFicheros;
    private javax.swing.JMenuItem menuLecturaBD;
    private javax.swing.JMenuItem menuLeerFichero;
    // End of variables declaration//GEN-END:variables
}
